### ISSUE TITLE
字段名称默认不带下划线如何修改？

### ISSUE THREAD

**Issue by iNuoers** [T-Manson/Dragon#1]
字段名称默认不带下划线如何修改？系统默认的是userName会拆成‘user_name’，这个怎么设置成使用PascalCase模式？

**Comment by T-Manson** [comment]
可以参考Dragon.Samples.WepApi文件夹下，appsettings.json文件内Data节点下的Dapper配置。

详情见标记部分：
"Data": {
    "DefaultConnectionName": "default",
    "ConnectionStrings": {
      "default": {
        "ConnectionString": "server=127.0.0.1;Database=mytest;UID=root;PWD=root;SslMode=None;",
        "DatabaseProviderType": "MySql"
      }
      //,
      //"write": {
      //  "ConnectionString": "server=;Database=;UID=;PWD=;Charset=utf8;SslMode=None;",
      //  "DatabaseProviderType": "SqlServer"
      //}
    },
    "Dapper": {
      "DbIdentifierMappingStrategy": "Underline",
      "CapitalizationRule": "LowerCase"

      **// 数据库映射规则（驼峰）
      //"DbIdentifierMappingStrategy": "PascalCase",
      // 大小写规则（与定义一致）
      //"CapitalizationRule": "Original"**

    }
  }

谢谢。

**Comment by iNuoers** [comment]
好的，感谢！
